<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FlightBooking.Domain\FlightBooking.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\Airports\" />
    <Folder Include="DTOs\flights\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Services\Airports\" />
    <Folder Include="Services\Flights\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
