// <auto-generated />
using System;
using FlightBooking.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlightBooking.Infrastructure.Migrations
{
    [DbContext(typeof(FlightBookingDbContext))]
    [Migration("20260928074901_SeedSampleData")]
    partial class SeedSampleData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlightBooking.Domain.Entities.Aircraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeatCapacity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Aircraft");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Model = "Airbus A320",
                            Registration = "VH-ABC",
                            SeatCapacity = 180
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Model = "Boeing 787-9",
                            Registration = "VH-XYZ",
                            SeatCapacity = 296
                        });
                });

            modelBuilder.Entity("FlightBooking.Domain.Entities.Airport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Airports");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            City = "Sydney",
                            Code = "SYD",
                            Country = "Australia",
                            Name = "Sydney Kingsford Smith"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            City = "Tokyo",
                            Code = "HND",
                            Country = "Japan",
                            Name = "Tokyo Haneda"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            City = "Singapore",
                            Code = "SIN",
                            Country = "Singapore",
                            Name = "Singapore Changi"
                        });
                });

            modelBuilder.Entity("FlightBooking.Domain.Entities.Flight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AircraftId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArrivalAirportId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartureAirportId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("ArrivalAirportId");

                    b.HasIndex("DepartureAirportId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            AircraftId = new Guid("55555555-5555-5555-5555-555555555555"),
                            ArrivalAirportId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ArrivalTime = new DateTime(2027, 3, 15, 18, 0, 0, 0, DateTimeKind.Utc),
                            DepartureAirportId = new Guid("11111111-1111-1111-1111-111111111111"),
                            DepartureTime = new DateTime(2027, 3, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            FlightNumber = "FB101",
                            Price = 850m
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            AircraftId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ArrivalAirportId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ArrivalTime = new DateTime(2027, 3, 16, 10, 0, 0, 0, DateTimeKind.Utc),
                            DepartureAirportId = new Guid("22222222-2222-2222-2222-222222222222"),
                            DepartureTime = new DateTime(2027, 3, 16, 2, 0, 0, 0, DateTimeKind.Utc),
                            FlightNumber = "FB202",
                            Price = 420m
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            AircraftId = new Guid("55555555-5555-5555-5555-555555555555"),
                            ArrivalAirportId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ArrivalTime = new DateTime(2027, 3, 18, 18, 0, 0, 0, DateTimeKind.Utc),
                            DepartureAirportId = new Guid("33333333-3333-3333-3333-333333333333"),
                            DepartureTime = new DateTime(2027, 3, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            FlightNumber = "FB303",
                            Price = 610m
                        });
                });

            modelBuilder.Entity("FlightBooking.Domain.Entities.Flight", b =>
                {
                    b.HasOne("FlightBooking.Domain.Entities.Aircraft", "Aircraft")
                        .WithMany()
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightBooking.Domain.Entities.Airport", "ArrivalAirport")
                        .WithMany()
                        .HasForeignKey("ArrivalAirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightBooking.Domain.Entities.Airport", "DepartureAirport")
                        .WithMany()
                        .HasForeignKey("DepartureAirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aircraft");

                    b.Navigation("ArrivalAirport");

                    b.Navigation("DepartureAirport");
                });
#pragma warning restore 612, 618
        }
    }
}
